# image will be published to ghcr.io/<user>/<name>
name: zima-blue
# description will be included in the image's metadata
description: nesv's custom uBlue image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - hyprland
      - hyprland-devel
      - hyprland-protocols-devel
      - xdg-desktop-portal-hyprland
      - qt5-qtwayland
      - qt6-qtwayland
      - waybar
      - dunst
      - starship
      - kitty
      - zathura
      - zathura-bash-completion
      - zathura-plugins-all
      - zathura-zsh-completion
      - sddm-wayland-generic
      - sddm-themes
      - pipewire
      - wireplumber
      - easyeffects
      - tailscale
      - git-all
      - fossil
      - mercurial
      - subversion
      - cvs
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (user)"

  - type: fonts
    fonts:
      nerd-fonts:
        - CascadiaMono
        - CodeNewRoman
        - FiraCode
        - Go-Mono
        - Hack
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Atkinson Hyperlegible
